services:
  aspiresync:
    privileged: true  # required for juicefs
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: devbuild
    environment:
      DB_HOST: ${DB_HOST:-db.aspiredev.org}
      DB_NAME: ${DB_NAME:-aspirecloud}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-password}
      DB_SCHEMA: ${DB_SCHEMA:-public}
      JUICEFS_BUCKET: ${JUICEFS_BUCKET}
      JUICEFS_ACCESS_KEY: ${JUICEFS_ACCESS_KEY}
      JUICEFS_SECRET_KEY: ${JUICEFS_SECRET_KEY}
    networks:
      - app-net
      - aspire-net
    volumes:
      - .:/opt/aspiresync
    # entrypoint: ['/opt/aspiresync/bin/aspiresync']  # good for prod, annoying in dev
    tty: true   # keeps the container running

networks:
  app-net: ~
  aspire-net:
    external: true
